package Final_DBMS_Project.src.main.java.DB_project.Teacher;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import Final_DBMS_Project.src.main.java.DB_project.Controller.Controller;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

/**
 *
 * @author Lenovo
 */
public class Teacher_Home extends javax.swing.JFrame {

    /**
     * Creates new form Teacher_Home
     */
    public Teacher_Home() {
        initComponents();

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        date_selected = now.getDayOfMonth();
        month_selected = now.getMonth().toString();
        year_selected = now.getYear();

        datebox.setSelectedItem(String.valueOf(date_selected));
        monthbox.setSelectedItem(month_selected);
        yearbox.setSelectedItem(String.valueOf(year_selected));

       Controller.setStudent_dropdown(student_dropdown);
       Controller.setResult_section_box(result_section_box);
        Controller.setSectionbox(sectionbox);
        Controller.set_sections(Controller.getUser().user_id);
        sectionbox.setSelectedIndex(0);
        Controller.setStudent_marks(student_marks);
        Controller.set_courses(Controller.getUser().user_id, sectionbox.getSelectedItem().toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTabbedPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        view_profile_btn = new javax.swing.JButton();
        mark_attendance_btn = new javax.swing.JButton();
        update_results_btn = new javax.swing.JButton();
        timetable_btn = new javax.swing.JButton();
        welcome_label = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        sectionbox = new javax.swing.JComboBox<>();
        select_section = new javax.swing.JLabel();
        select_course = new javax.swing.JLabel();
        coursebox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        set_date = new javax.swing.JLabel();
        datebox = new javax.swing.JComboBox<>();
        set_month = new javax.swing.JLabel();
        monthbox = new javax.swing.JComboBox<>();
        set_year = new javax.swing.JLabel();
        yearbox = new javax.swing.JComboBox<>();
        update_attendance_button = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        select_Rsection = new javax.swing.JLabel();
        result_section_box = new javax.swing.JComboBox<>();
        select_student = new javax.swing.JLabel();
        student_dropdown = new javax.swing.JComboBox<>();
        marks_label = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        update_results = new javax.swing.JButton();
        student_marks = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        select_Rsection1 = new javax.swing.JLabel();
        result_course_menu = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Bahama International College");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        view_profile_btn.setBackground(new java.awt.Color(255, 204, 0));
        view_profile_btn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        view_profile_btn.setText("View Profile");
        view_profile_btn.setBorderPainted(false);
        view_profile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_profile_btnActionPerformed(evt);
            }
        });

        mark_attendance_btn.setBackground(new java.awt.Color(255, 204, 0));
        mark_attendance_btn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        mark_attendance_btn.setText("Mark Attendance");
        mark_attendance_btn.setBorderPainted(false);
        mark_attendance_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark_attendance_btnActionPerformed(evt);
            }
        });

        update_results_btn.setBackground(new java.awt.Color(255, 204, 0));
        update_results_btn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        update_results_btn.setText("Update Results");
        update_results_btn.setBorderPainted(false);

        timetable_btn.setBackground(new java.awt.Color(255, 204, 0));
        timetable_btn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        timetable_btn.setText("Timetable");
        timetable_btn.setBorderPainted(false);

        welcome_label.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        welcome_label.setForeground(new java.awt.Color(255, 204, 0));
        welcome_label.setText("Welcome User");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcome_label, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(update_results_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                            .addComponent(timetable_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(view_profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mark_attendance_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(welcome_label)
                .addGap(118, 118, 118)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_profile_btn)
                    .addComponent(mark_attendance_btn))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_results_btn)
                    .addComponent(timetable_btn))
                .addContainerGap(313, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Home", jPanel3);

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));

        sectionbox.setEditable(true);
        sectionbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SG-1", "AG-1" }));
        sectionbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionboxActionPerformed(evt);
            }
        });

        select_section.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        select_section.setForeground(new java.awt.Color(255, 204, 0));
        select_section.setText("Select Section");

        select_course.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        select_course.setForeground(new java.awt.Color(255, 204, 0));
        select_course.setText("Select Course");

        coursebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Urdu", "Sociology", "History", "psychology", "Science", "Computer", "Mathematics" }));
        coursebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseboxActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {1, "", ""},
                {2, "", ""},
                {3, "", ""},
                {4, "", ""},
                {5, "", ""},
                {6, "", "Present"},
                {7, "", "Present"},
                {8, "", ""},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        set_date.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        set_date.setForeground(new java.awt.Color(255, 204, 0));
        set_date.setText("Select Date");

        datebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        datebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateboxActionPerformed(evt);
            }
        });

        set_month.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        set_month.setForeground(new java.awt.Color(255, 204, 0));
        set_month.setText("Select Month");

        monthbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));
        monthbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthboxActionPerformed(evt);
            }
        });

        set_year.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        set_year.setForeground(new java.awt.Color(255, 204, 0));
        set_year.setText("Select Year");

        yearbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019" }));
        yearbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearboxActionPerformed(evt);
            }
        });

        update_attendance_button.setBackground(new java.awt.Color(255, 204, 0));
        update_attendance_button.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        update_attendance_button.setText("Update");
        update_attendance_button.setBorderPainted(false);
        update_attendance_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_attendance_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coursebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_course)
                    .addComponent(select_section)
                    .addComponent(set_date)
                    .addComponent(set_month)
                    .addComponent(set_year)
                    .addComponent(sectionbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datebox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthbox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearbox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addComponent(update_attendance_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_attendance_button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addComponent(select_section)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sectionbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(select_course)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coursebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(set_date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datebox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(set_month)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthbox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(set_year)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))))
        );

        JTabbedPane.addTab("Attendance", jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 0, 51));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"BESE-8a", "12 PM - 1 PM", "9 AM - 11 AM", "9 AM - 11 AM", "12 PM - 1 PM", "12 PM - 1 PM"},
                {"BESE-8b", "12 PM - 1 PM", "12 PM - 1 PM", "12 PM - 1 PM", "12 PM - 1 PM", "12 PM - 1 PM"}
            },
            new String [] {
                "", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 0));
        jLabel9.setText("Timetable for Ma'am");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 0));
        jLabel10.setText("Your next class starts in an hour");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Timetable", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 0, 51));

        select_Rsection.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        select_Rsection.setForeground(new java.awt.Color(255, 204, 0));
        select_Rsection.setText("Select Section");

        result_section_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_section_boxActionPerformed(evt);
            }
        });

        select_student.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        select_student.setForeground(new java.awt.Color(255, 204, 0));
        select_student.setText("Select Student");

        student_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        student_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_dropdownActionPerformed(evt);
            }
        });

        marks_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        marks_label.setForeground(new java.awt.Color(255, 204, 0));
        marks_label.setText("Marks:");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 0));

        update_results.setBackground(new java.awt.Color(255, 204, 0));
        update_results.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        update_results.setText("Update");
        update_results.setBorderPainted(false);
        update_results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_resultsActionPerformed(evt);
            }
        });

        student_marks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_marksActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 0));
        jLabel15.setText("/100");

        select_Rsection1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        select_Rsection1.setForeground(new java.awt.Color(255, 204, 0));
        select_Rsection1.setText("Select Course");

        result_course_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_course_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(update_results, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(marks_label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(select_Rsection)
                                .addGap(58, 58, 58)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(student_marks, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(result_section_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(select_student)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(select_Rsection1)
                                        .addGap(58, 58, 58)))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(student_dropdown, 0, 112, Short.MAX_VALUE)
                                    .addComponent(result_course_menu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)))
                .addContainerGap(428, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_Rsection)
                    .addComponent(result_section_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(select_Rsection1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(result_course_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel14)
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_student)
                    .addComponent(student_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marks_label)
                    .addComponent(student_marks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(43, 43, 43)
                .addComponent(update_results)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Results", jPanel7);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTabbedPane)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void student_marksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_marksActionPerformed
        // TODO add your handling code here:
        int ob_marks=Integer.parseInt(student_marks.getText());
    }//GEN-LAST:event_student_marksActionPerformed

    private void student_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_dropdownActionPerformed
        // TODO add your handling code here:
        student = student_dropdown.getSelectedItem().toString();
        Controller.fetch_student_result(student, course, section);
    }//GEN-LAST:event_student_dropdownActionPerformed

    private void sectionboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionboxActionPerformed
        // TODO add your handling code here:
        section = sectionbox.getSelectedItem().toString();
        if(Controller.getCoursebox() == null){
            Controller.setCoursebox(coursebox);
            Controller.setAttendance_table(jTable1);
            Controller.setResult_course_menu(result_course_menu);
        }
        Controller.set_courses(Controller.getUser().user_id, section);
        coursebox.setSelectedIndex(0);
        course = coursebox.getItemAt(0);
        Controller.set_students();
        Controller.display_attendance(section, course, date_selected, monthbox.getSelectedItem().toString(), year_selected);
    }//GEN-LAST:event_sectionboxActionPerformed

    private void mark_attendance_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark_attendance_btnActionPerformed
        // TODO add your handling code here:
        jPanel5.setVisible(true);
    }//GEN-LAST:event_mark_attendance_btnActionPerformed

    private void view_profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_profile_btnActionPerformed
        // TODO add your handling code here:

        new Teachers_Profile().setVisible(true);
    }//GEN-LAST:event_view_profile_btnActionPerformed

    private void courseboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseboxActionPerformed
        // TODO add your handling code here:
        course = String.valueOf(coursebox.getSelectedItem().toString());
        //Controller.get_all_students(section);
        Controller.display_attendance(section, course, date_selected, monthbox.getSelectedItem().toString(), year_selected);
    }//GEN-LAST:event_courseboxActionPerformed

    private void result_section_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_section_boxActionPerformed
        // TODO add your handling code here:
        section = String.valueOf(result_section_box.getSelectedItem().toString());
        Controller.set_students();
    }//GEN-LAST:event_result_section_boxActionPerformed

    private void update_resultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_resultsActionPerformed
        // TODO add your handling code here:
        String marks = student_marks.getText();
        Controller.update_student_result(student, course, section, marks);
    }//GEN-LAST:event_update_resultsActionPerformed

    private void result_course_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_course_menuActionPerformed
        // TODO add your handling code here:
        course = result_course_menu.getSelectedItem().toString();
    }//GEN-LAST:event_result_course_menuActionPerformed

    private void dateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateboxActionPerformed
        // TODO add your handling code here:
        date_selected = Integer.parseInt(datebox.getSelectedItem().toString());
        Controller.display_attendance(section, course, date_selected, monthbox.getSelectedItem().toString(), year_selected);
    }//GEN-LAST:event_dateboxActionPerformed

    private void monthboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthboxActionPerformed
        // TODO add your handling code here:
        month_selected = monthbox.getSelectedItem().toString();
        Controller.display_attendance(section, course, date_selected, monthbox.getSelectedItem().toString(), year_selected);
    }//GEN-LAST:event_monthboxActionPerformed

    private void yearboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearboxActionPerformed
        // TODO add your handling code here:
        year_selected = Integer.parseInt(yearbox.getSelectedItem().toString());
        Controller.display_attendance(section, course, date_selected, monthbox.getSelectedItem().toString(), year_selected);
    }//GEN-LAST:event_yearboxActionPerformed

    private void update_attendance_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_attendance_buttonActionPerformed
        // TODO add your handling code here:
        Controller.update_attendance(course, date_selected, monthbox.getSelectedIndex(), year_selected);
    }//GEN-LAST:event_update_attendance_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_Home().setVisible(true);
            }
        });
    }

    private String section;
    private String course;
    private String student;
    private int date_selected;
    private String month_selected;
    private int year_selected;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JComboBox<String> coursebox;
    private javax.swing.JComboBox<String> datebox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton mark_attendance_btn;
    private javax.swing.JLabel marks_label;
    private javax.swing.JComboBox<String> monthbox;
    private javax.swing.JComboBox<String> result_course_menu;
    private javax.swing.JComboBox<String> result_section_box;
    private javax.swing.JComboBox<String> sectionbox;
    private javax.swing.JLabel select_Rsection;
    private javax.swing.JLabel select_Rsection1;
    private javax.swing.JLabel select_course;
    private javax.swing.JLabel select_section;
    private javax.swing.JLabel select_student;
    private javax.swing.JLabel set_date;
    private javax.swing.JLabel set_month;
    private javax.swing.JLabel set_year;
    private javax.swing.JComboBox<String> student_dropdown;
    private javax.swing.JTextField student_marks;
    private javax.swing.JButton timetable_btn;
    private javax.swing.JButton update_attendance_button;
    private javax.swing.JButton update_results;
    private javax.swing.JButton update_results_btn;
    private javax.swing.JButton view_profile_btn;
    private javax.swing.JLabel welcome_label;
    private javax.swing.JComboBox<String> yearbox;
    // End of variables declaration//GEN-END:variables
}
