/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Final_DBMS_Project.src.main.java.DB_project;

import Final_DBMS_Project.src.main.java.DB_project.Admin.Admin_Home;
import Final_DBMS_Project.src.main.java.DB_project.Controller.Controller;
import Final_DBMS_Project.src.main.java.DB_project.Entities.User;
import Final_DBMS_Project.src.main.java.DB_project.Librarian.Librarian_Home;
import Final_DBMS_Project.src.main.java.DB_project.Model.Model;
import Final_DBMS_Project.src.main.java.DB_project.Teacher.Teacher_Home;
import Final_DBMS_Project.src.main.java.DB_project.connect.JavaConnectDB;

import javax.swing.*;

/**
 *
 * @author Hp
 */
public class LogIn extends JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        jTabbedPane1 = new JTabbedPane();
        jPanel5 = new JPanel();
        jLabel2 = new JLabel();
        AID = new JTextField();
        jLabel3 = new JLabel();
        AsignIn = new JButton();
        Apass = new JPasswordField();
        jPanel4 = new JPanel();
        FsignIn = new JButton();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        FID = new JTextField();
        Fpass = new JPasswordField();
        jPanel3 = new JPanel();
        jPanel6 = new JPanel();
        LsignIn = new JButton();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        LID = new JTextField();
        Lpass = new JPasswordField();
        JLabel jLabel8 = new JLabel();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 100, 0));

        jLabel8.setIcon(new ImageIcon("E:\\4th sem\\DBMS\\FINAL PROJECT\\src\\Final_DBMS_Project\\src\\resources\\APS logo sm.png")); // NOI18N
        jLabel8.setText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)
                                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel8)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new ImageIcon("E:\\4th sem\\DBMS\\FINAL PROJECT\\src\\Final_DBMS_Project\\src\\resources\\APS LOGO Large.png")); // NOI18N
        jLabel1.setText("Army Public School And College Westridge 3");

        jTabbedPane1.setBackground(new java.awt.Color(0,100,0));
        jTabbedPane1.setOpaque(true);

        jPanel5.setBackground(new java.awt.Color(25,255,255));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0,100,0));
        jLabel2.setText("LogIn ID:");

        AID.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        AID.setToolTipText("LogIn ID");
        AID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0,100,0));
        jLabel3.setText("Password:");

        AsignIn.setBackground(new java.awt.Color(0,100,0));
        AsignIn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        AsignIn.setText("Admin SignIn");
        AsignIn.setBorderPainted(false);
        AsignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignInActionPerformed(evt);
            }
        });

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AsignIn, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Apass)
                    .addComponent(jLabel2, GroupLayout.Alignment.LEADING)
                    .addComponent(AID, GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jLabel3, GroupLayout.Alignment.LEADING))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AID, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Apass, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(AsignIn, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Login as Admin", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255,255,255));

        FsignIn.setBackground(new java.awt.Color(0,100,0));
        FsignIn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        FsignIn.setText("Faculty SignIn");
        FsignIn.setBorderPainted(false);
        FsignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FsignInActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0,100,0));
        jLabel4.setText("LogIn ID:");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0,100,0));
        jLabel5.setText("Password:");

        FID.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        FID.setToolTipText("LogIn ID");
        FID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIDActionPerformed(evt);
            }
        });

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FsignIn, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Fpass)
                    .addComponent(jLabel4, GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, GroupLayout.Alignment.LEADING)
                    .addComponent(FID, GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FID, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addComponent(Fpass, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FsignIn, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("Login as Faculty", jPanel4);

        jPanel3.setBackground(new java.awt.Color(255,255,255));

        jPanel6.setBackground(new java.awt.Color(255,255,255));

        LsignIn.setBackground(new java.awt.Color(0,100,0));
        LsignIn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        LsignIn.setText("Librarian SignIn");
        LsignIn.setBorderPainted(false);
        LsignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LsignInActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0,100,0));
        jLabel6.setText("LogIn ID:");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0,100,0));
        jLabel7.setText("Password:");

        LID.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        LID.setToolTipText("LogIn ID");
        LID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIDActionPerformed(evt);
            }
        });

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 289, Short.MAX_VALUE)
                        .addComponent(LsignIn))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(LID, GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(Lpass))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LID, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lpass, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LsignIn, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Login as Librarian", jPanel3);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 479, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 327, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 252, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 233, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AIDActionPerformed

    private void AsignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignInActionPerformed
        String username = AID.getText();
        String password = Apass.getText();

        Model.connect();
        User user = Model.authenticate_user(username, password);
            if (AID.getText().isBlank() || Apass.getText().isBlank()) {
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f, "Please, Enter valid fields");
            } else if (user !=null) {
                Controller.setUser(user);
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new Admin_Home(Integer.parseInt(AID.getText())).setVisible(true);
                        }
                    });
                    this.dispose();
                }
            else{
                    JFrame f = new JFrame();
                    JOptionPane.showMessageDialog(f, "User Does not Exists");
                }
        }//GEN-LAST:event_AsignInActionPerformed

    private void FsignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FsignInActionPerformed
        String username = FID.getText();
        String password = Fpass.getText();

        Model.connect();
        User user = Model.authenticate_user(username, password);
        if(FID.getText().isBlank() || Fpass.getText().isBlank()){
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Please, Enter valid fields");
        }else if(user != null){
                Controller.setUser(user);
                this.dispose();
                new Teacher_Home().setVisible(true);

            }
            else{
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "User Does not Exists");
            }
    }//GEN-LAST:event_FsignInActionPerformed

    private void FIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIDActionPerformed

    private void LsignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LsignInActionPerformed
        String username = LID.getText();
        String password = Lpass.getText();

        Model.connect();
        User user = Model.authenticate_user(username, password);
        if(LID.getText().isBlank() || Lpass.getText().isBlank()){
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Please, Enter all fields");
        }else if (user != null){
                Controller.setUser(user);
                new Librarian_Home().setVisible(true);
            this.dispose();
        }
        else{
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "User Does not Exists");
        }
    }//GEN-LAST:event_LsignInActionPerformed

    private void LIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_LIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField AID;
    private JPasswordField Apass;
    private JButton AsignIn;
    private JTextField FID;
    private JPasswordField Fpass;
    private JButton FsignIn;
    private JTextField LID;
    private JPasswordField Lpass;
    private JButton LsignIn;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JTabbedPane jTabbedPane1;

    // End of variables declaration//GEN-END:variables
}
