package Final_DBMS_Project.src.main.java.DB_project.Librarian;/*

 *
 * @author Hp
 */

import Final_DBMS_Project.src.main.java.DB_project.LogIn;
import Final_DBMS_Project.src.main.java.DB_project.Tables.all_books;
import Final_DBMS_Project.src.main.java.DB_project.Tables.availble_books;
import Final_DBMS_Project.src.main.java.DB_project.checks;
import Final_DBMS_Project.src.main.java.DB_project.connect.JavaConnectDB;

import javax.swing.*;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Librarian_Home extends javax.swing.JFrame {

    /**
     * Creates new form Librarian_Home1
     */
    public Librarian_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logout_button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        book_return_tab = new javax.swing.JTabbedPane();
        home_tab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        view_all_books = new javax.swing.JButton();
        view_available_books = new javax.swing.JButton();
        issue_book_panel = new javax.swing.JPanel();
        select_book_label = new javax.swing.JLabel();
        books_combo_box = new javax.swing.JComboBox<>();
        select_book_label1 = new javax.swing.JLabel();
        stu_discipline = new javax.swing.JLabel();
        science_radioButton = new javax.swing.JRadioButton();
        arts_radioButton = new javax.swing.JRadioButton();
        stu_roll_field = new javax.swing.JTextField();
        date_issue_label = new javax.swing.JLabel();
        date_return_label = new javax.swing.JLabel();
        date_issue_field = new javax.swing.JTextField();
        date_return_field = new javax.swing.JTextField();
        issue_book_button = new javax.swing.JButton();
        book_return_panel = new javax.swing.JPanel();
        select_return_book_label = new javax.swing.JLabel();
        return_books_combo_box = new javax.swing.JComboBox<>();
        return_book_button = new javax.swing.JButton();
        return_text_tabel = new javax.swing.JLabel();
        add_book_panel = new javax.swing.JPanel();
        select_return_book_label1 = new javax.swing.JLabel();
        book_name_field = new javax.swing.JTextField();
        book_category_label = new javax.swing.JLabel();
        category_combo_box = new javax.swing.JComboBox<>();
        add_book = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));
        jPanel3.setForeground(new java.awt.Color(255, 204, 0));

        jLabel3.setIcon(new ImageIcon("E:\\4th sem\\DBMS\\FINAL PROJECT\\src\\Final_DBMS_Project\\src\\resources\\logo snip.PNG")); // NOI18N

        logout_button.setBackground(new java.awt.Color(0, 0, 51));
        logout_button.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        logout_button.setForeground(new java.awt.Color(255, 255, 255));
        logout_button.setText("Logout");
        logout_button.setBorderPainted(false);
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(logout_button)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                                .addComponent(logout_button)
                                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Army Public School and College Westridge III");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)
                                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(23, Short.MAX_VALUE))
        );

        book_return_tab.setBackground(new java.awt.Color(255,255,255));
        book_return_tab.setForeground(new java.awt.Color(255,255,255));

        home_tab.setBackground(new java.awt.Color(255,255,255));
        home_tab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setIcon(new ImageIcon("E:\\4th sem\\DBMS\\FINAL PROJECT\\src\\Final_DBMS_Project\\src\\resources\\college  small.jpg")); // NOI18N
        jLabel6.setText("jLabel6");

        view_all_books.setBackground(new java.awt.Color(0,100, 0));
        view_all_books.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        view_all_books.setText("View All Books");
        view_all_books.setBorderPainted(false);
        view_all_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_all_booksActionPerformed(evt);
            }
        });

        view_available_books.setBackground(new java.awt.Color(0,100, 0));
        view_available_books.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        view_available_books.setText("View Available Books");
        view_available_books.setBorderPainted(false);
        view_available_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_available_booksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout home_tabLayout = new javax.swing.GroupLayout(home_tab);
        home_tab.setLayout(home_tabLayout);
        home_tabLayout.setHorizontalGroup(
                home_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(home_tabLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(home_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(view_all_books, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(view_available_books))
                                .addContainerGap(59, Short.MAX_VALUE))
        );
        home_tabLayout.setVerticalGroup(
                home_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(home_tabLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(view_all_books)
                                .addGap(29, 29, 29)
                                .addComponent(view_available_books)
                                .addContainerGap(60, Short.MAX_VALUE))
        );

        book_return_tab.addTab("Home", home_tab);

        issue_book_panel.setBackground(new java.awt.Color(255,255,255));

        select_book_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        select_book_label.setForeground(new java.awt.Color(0,100, 0));
        select_book_label.setText("Select Book:");
        ResultSet rs = JavaConnectDB.availableBooks();
        try{
            while(rs.next()){
                String name = rs.getString("name");
                books_combo_box.addItem(name);
            }
        }catch (SQLException e){

        }

        select_book_label1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        select_book_label1.setForeground(new java.awt.Color(0,100,0));
        select_book_label1.setText("Student roll:");

        stu_discipline.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        stu_discipline.setForeground(new java.awt.Color(0,100,0));
        stu_discipline.setText("Discipline:");

        science_radioButton.setBackground(new java.awt.Color(255,255,255));
        science_radioButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        science_radioButton.setForeground(new java.awt.Color(255, 204, 0));
        science_radioButton.setText("Science");
        science_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                science_radioButtonActionPerformed(evt);
            }
        });

        arts_radioButton.setBackground(new java.awt.Color(255,255,255));
        arts_radioButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        arts_radioButton.setForeground(new java.awt.Color(0,100,0));
        arts_radioButton.setText("Arts");
        arts_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arts_radioButtonActionPerformed(evt);
            }
        });

        stu_roll_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stu_roll_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_roll_fieldActionPerformed(evt);
            }
        });

        date_issue_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        date_issue_label.setForeground(new java.awt.Color(0,100,0));
        date_issue_label.setText("Date issue:");
        date_return_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        date_return_label.setForeground(new java.awt.Color(0,100,0));
        date_return_label.setText("Date Return:");

        date_issue_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date_issue_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_issue_fieldActionPerformed(evt);
            }
        });

        date_return_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date_return_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_return_fieldActionPerformed(evt);
            }
        });

        issue_book_button.setBackground(new java.awt.Color(255, 204, 0));
        issue_book_button.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        issue_book_button.setText("Issue Book");
        issue_book_button.setBorderPainted(false);
        issue_book_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue_book_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout issue_book_panelLayout = new javax.swing.GroupLayout(issue_book_panel);
        issue_book_panel.setLayout(issue_book_panelLayout);
        issue_book_panelLayout.setHorizontalGroup(
                issue_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(issue_book_panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(issue_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(issue_book_panelLayout.createSequentialGroup()
                                                .addComponent(stu_discipline)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(science_radioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(arts_radioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(85, 85, 85))
                                        .addGroup(issue_book_panelLayout.createSequentialGroup()
                                                .addComponent(select_book_label1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(stu_roll_field, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(63, 63, 63))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, issue_book_panelLayout.createSequentialGroup()
                                                .addGroup(issue_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(issue_book_panelLayout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(issue_book_button, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(issue_book_panelLayout.createSequentialGroup()
                                                                .addGroup(issue_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(date_issue_label)
                                                                        .addComponent(date_return_label))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                                                .addGroup(issue_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(date_issue_field, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(date_return_field, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(63, 63, 63))
                                        .addGroup(issue_book_panelLayout.createSequentialGroup()
                                                .addComponent(select_book_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(books_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(204, 204, 204))))
        );
        issue_book_panelLayout.setVerticalGroup(
                issue_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(issue_book_panelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(issue_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(issue_book_panelLayout.createSequentialGroup()
                                                .addGroup(issue_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(select_book_label)
                                                        .addComponent(books_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(issue_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(select_book_label1)
                                                        .addComponent(stu_roll_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(issue_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(stu_discipline)
                                                        .addComponent(science_radioButton)
                                                        .addComponent(arts_radioButton))
                                                .addGap(18, 18, 18)
                                                .addComponent(date_issue_label))
                                        .addComponent(date_issue_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(issue_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(date_return_label)
                                        .addComponent(date_return_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(issue_book_button)
                                .addContainerGap(57, Short.MAX_VALUE))
        );

        book_return_tab.addTab("Issue Book", issue_book_panel);

        book_return_panel.setBackground(new java.awt.Color(0, 0, 51));

        select_return_book_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        select_return_book_label.setForeground(new java.awt.Color(255, 204, 0));
        select_return_book_label.setText("Select Book:");

        try{
            ResultSet rs1 = JavaConnectDB.notAvailableBooks();
            while (rs1.next()){
                return_books_combo_box.addItem(rs1.getString("name"));
            }
        }
        catch (SQLException e){
            e.printStackTrace();
        }
        return_book_button.setBackground(new java.awt.Color(255, 204, 0));
        return_book_button.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        return_book_button.setText("Update");
        return_book_button.setBorderPainted(false);
        return_book_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_book_buttonActionPerformed(evt);
            }
        });

        return_text_tabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        return_text_tabel.setForeground(new java.awt.Color(255, 204, 0));
        return_text_tabel.setText("Select Book to be returned to Collection:");

        javax.swing.GroupLayout book_return_panelLayout = new javax.swing.GroupLayout(book_return_panel);
        book_return_panel.setLayout(book_return_panelLayout);
        book_return_panelLayout.setHorizontalGroup(
                book_return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(book_return_panelLayout.createSequentialGroup()
                                .addGroup(book_return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(book_return_panelLayout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(book_return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(return_text_tabel)
                                                        .addGroup(book_return_panelLayout.createSequentialGroup()
                                                                .addComponent(select_return_book_label)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(return_books_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(book_return_panelLayout.createSequentialGroup()
                                                .addGap(172, 172, 172)
                                                .addComponent(return_book_button, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(161, Short.MAX_VALUE))
        );
        book_return_panelLayout.setVerticalGroup(
                book_return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(book_return_panelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(return_text_tabel)
                                .addGap(37, 37, 37)
                                .addGroup(book_return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(select_return_book_label)
                                        .addComponent(return_books_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(return_book_button)
                                .addContainerGap(185, Short.MAX_VALUE))
        );

        book_return_tab.addTab("Book return", book_return_panel);

        add_book_panel.setBackground(new java.awt.Color(0, 0, 51));

        select_return_book_label1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        select_return_book_label1.setForeground(new java.awt.Color(255, 204, 0));
        select_return_book_label1.setText("Name:");

        book_name_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        book_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_name_fieldActionPerformed(evt);
            }
        });

        book_category_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        book_category_label.setForeground(new java.awt.Color(255, 204, 0));
        book_category_label.setText("Category:");

        category_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        add_book.setBackground(new java.awt.Color(255, 204, 0));
        add_book.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        add_book.setText("Add");
        add_book.setBorderPainted(false);
        add_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_book_panelLayout = new javax.swing.GroupLayout(add_book_panel);
        add_book_panel.setLayout(add_book_panelLayout);
        add_book_panelLayout.setHorizontalGroup(
                add_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_book_panelLayout.createSequentialGroup()
                                .addGroup(add_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(add_book_panelLayout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(add_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(book_category_label)
                                                        .addComponent(select_return_book_label1))
                                                .addGap(71, 71, 71)
                                                .addGroup(add_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(book_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(category_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(add_book_panelLayout.createSequentialGroup()
                                                .addGap(201, 201, 201)
                                                .addComponent(add_book, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(97, Short.MAX_VALUE))
        );
        add_book_panelLayout.setVerticalGroup(
                add_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_book_panelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(add_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(select_return_book_label1)
                                        .addComponent(book_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(add_book_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(book_category_label)
                                        .addComponent(category_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(add_book)
                                .addContainerGap(150, Short.MAX_VALUE))
        );

        book_return_tab.addTab("Add book", add_book_panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(book_return_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(book_return_tab)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        issue_stu_disc.add(science_radioButton);
        issue_stu_disc.add(arts_radioButton);

        pack();
    }// </editor-fold>

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        new LogIn().setVisible(true);
    }

    private void view_available_booksActionPerformed(java.awt.event.ActionEvent evt) {
        new availble_books(JavaConnectDB.availableBooks());
    }

    private void view_all_booksActionPerformed(java.awt.event.ActionEvent evt) {
        new all_books(JavaConnectDB.allBooks());
    }

    private void science_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        disc_selected += "science";
    }

    private void arts_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        disc_selected += "science";
    }

    private void stu_roll_fieldActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void date_issue_fieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void date_return_fieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void issue_book_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        String exist = JavaConnectDB.studentExist(Integer.parseInt(stu_roll_field.getText()), disc_selected);
        if(!checks.validInteger(stu_roll_field.getText()) || exist == null || stu_roll_field.getText().isBlank()
        ||date_issue_field.getText().isBlank() || date_return_field.getText().isBlank()){
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Please, enter valid fields");
        }
        else{
            JavaConnectDB.issueBook(books_combo_box.getSelectedItem().toString(), Integer.parseInt(stu_roll_field.getText()), date_issue_field.getText(), date_return_field.getText(), disc_selected);
        }
    }

    private void return_book_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        JavaConnectDB.returnBook(return_books_combo_box.getSelectedItem().toString());
    }

    private void book_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void add_bookActionPerformed(java.awt.event.ActionEvent evt) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librarian_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librarian_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librarian_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librarian_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librarian_Home().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify
    private javax.swing.JButton add_book;
    private javax.swing.JPanel add_book_panel;
    private javax.swing.JRadioButton arts_radioButton;
    private javax.swing.JLabel book_category_label;
    private javax.swing.JTextField book_name_field;
    private javax.swing.JPanel book_return_panel;
    private javax.swing.JTabbedPane book_return_tab;
    private javax.swing.JComboBox<String> books_combo_box;
    private javax.swing.JComboBox<String> category_combo_box;
    private javax.swing.JTextField date_issue_field;
    private javax.swing.JLabel date_issue_label;
    private javax.swing.JTextField date_return_field;
    private javax.swing.JLabel date_return_label;
    private javax.swing.JPanel home_tab;
    private javax.swing.JButton issue_book_button;
    private javax.swing.JPanel issue_book_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logout_button;
    private javax.swing.JButton return_book_button;
    private javax.swing.JComboBox<String> return_books_combo_box;
    private javax.swing.JLabel return_text_tabel;
    private javax.swing.JRadioButton science_radioButton;
    private javax.swing.JLabel select_book_label;
    private javax.swing.JLabel select_book_label1;
    private javax.swing.JLabel select_return_book_label;
    private javax.swing.JLabel select_return_book_label1;
    private javax.swing.JLabel stu_discipline;
    private javax.swing.JTextField stu_roll_field;
    private javax.swing.JButton view_all_books;
    private javax.swing.JButton view_available_books;
    ButtonGroup issue_stu_disc = new ButtonGroup();
    String disc_selected = "";
    // End of variables declaration
}
